### ISSUE TITLE
关于 学习-图书馆部分

### ISSUE THREAD

**Issue by infinitylin** [FsHtroy/ZSC-New-member-Q-A#10]
在图书馆的部分，我这边有几个推荐的补充选项。这些内容*不一定*都要放进Q&A之中，仅作参考。

FYI：因为对于我来说图书馆相对于自习，更像是一个资源库，所以我只会着重对书籍和资源进行补充。

1. 借书相关
在图书馆的官网描述中[这里](http://lib.zsc.edu.cn/in_guide.asp)，一般学生最多可以借阅中文图书 15 本，借期 60 天，可续借一次（ 30 天）。有个小特殊情况是，如果你的还书日期在寒暑假放假中的话，还书日期会自动延期到返校后，使用得当的话可以“延长”你的借阅时间。

2. 关于计算机书籍
学校的计算机类书籍已经非常丰富了，有些实体书较贵的经典书也会有，个人还是挺推荐大家在大学有空的时候找找自己需要的书看。并且可以通过购书推荐来让学校购买较新出版的书籍 [这里](http://210.38.224.62:8080/asord/asord_hist.php)

3. 毕业之后
有段时间我非常在意自己的借书记录，但是毕业之后就无法登陆图书馆系统了，但是还是有一个方便查阅自己的借书记录的：[您的借书印迹](http://210.38.224.60:81/gbook/index.php?controller=read&action=index)

4. 论文查询
这个很重要，很重要，很重要。在以前可以通过学校的 ip 在中国知网、万方 等重要的平台去**免费**下载有限量的论文。刚开始对论文需求不大一般没什么感觉。当需要这种服务的时候，就会觉得这是个非常好的资源了。

循例，metion 一下 @FsHtroy ，感谢花时间看完这个 issue

**Comment by FsHtroy** [comment]
Thanks.I will update later.

**Comment by FsHtroy** [comment]
Our admin Tsingchengliu update this issue in commit #27d9c29.
