### ISSUE TITLE
Add 720° view of school 

### ISSUE THREAD

**Issue by DarkNeoHQ** [FsHtroy/ZSC-New-member-Q-A#4]
just to help new student to have a view of UESTC,Zhongshan Institute

here is the door
http://www.gy720.com/pano/view/1739&v=ok

**Comment by hangxingliu** [comment]
good idea. 
@FsHtroy add into `README.md` if you think that it is good idea too

**Comment by FsHtroy** [comment]
Thanks for Darkneo support a link about 720° of school view.
